/**
 * 图标。**字形来自 lucide-react 1.17.0**（跟 memoket desktop 0.5.10 同一个版本
 * 同一个包，见 docs/MEMOKET_DESKTOP_0.5.10.md §3）。
 *
 * **名字仍然是 `bx-*`，这是故意的。** 这套名字已经长进了两个地方：
 * 用户在图标选择器里挑的图标**存在数据库里**（`setNoteIcon`），
 * 以及 `entityIcon` / `noteSource` 这些映射表。把名字也换掉意味着要迁移用户数据，
 * 而换名字对「像不像」没有任何贡献——**要换的是字形，不是词汇表**。
 * 所以这里只做一件事：把 `bx-*` 翻成 lucide 的组件。
 *
 * 两个让改动面变小的决定：
 * - `size="1em"`：SVG 跟着 `font-size` 走，于是现有那一大堆
 *   `.tree-icon .bx { font-size: var(--icon-nav) }` 这样的尺寸 CSS **一行都不用改**。
 * - 保留 `bx` 类名：上面那些选择器本来就是按 `.bx` 写的。
 *
 * 描边宽度：lucide 默认 2（24 的 viewBox）。0.5.10 大部分地方用默认值，
 * 个别位置调到 1.7–2.1。我们取默认，需要更细的地方单独传 `strokeWidth`。
 */
import {
  AlignLeft,
  AppWindow,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  Book,
  Bookmark,
  BookmarkPlus,
  Bot,
  Brain,
  Briefcase,
  Brush,
  Building2,
  Calculator,
  Calendar,
  CalendarDays,
  Camera,
  Car,
  ChartColumn,
  ChartLine,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsDownUp,
  ChevronsLeft,
  ChevronsRight,
  Circle,
  CircleCheck,
  CircleDollarSign,
  CircleHelp,
  CirclePause,
  CircleQuestionMark,
  CircleStop,
  Clock,
  Code,
  CodeXml,
  Coffee,
  Columns2,
  Command,
  Copy,
  CopyPlus,
  CornerDownRight,
  Cpu,
  Crosshair,
  Database,
  Download,
  Dumbbell,
  Ellipsis,
  Expand,
  ExternalLink,
  Eye,
  File,
  FileText,
  Files,
  Filter,
  Flag,
  Folder,
  FolderOpen,
  GitBranch,
  GitCommitHorizontal,
  GitCompare,
  GitMerge,
  Hash,
  Heading,
  Headphones,
  Heart,
  History,
  House,
  Image,
  ImagePlus,
  Images,
  Import,
  Info,
  Layers,
  LayoutGrid,
  Leaf,
  Lightbulb,
  Link,
  Link2,
  List,
  ListChecks,
  ListOrdered,
  ListTodo,
  LoaderCircle,
  Lock,
  Mail,
  Map,
  Maximize,
  Merge,
  MessageCircleMore,
  MessageSquare,
  MessagesSquare,
  Mic,
  MicOff,
  Monitor,
  Moon,
  MoveHorizontal,
  Music,
  NotebookText,
  Package,
  PaintBucket,
  Paintbrush,
  Palette,
  PanelTop,
  PenLine,
  PenTool,
  Pencil,
  Phone,
  Pin,
  Play,
  Plus,
  Presentation,
  Puzzle,
  Quote,
  RefreshCw,
  Rocket,
  RotateCcw,
  Save,
  Search,
  Send,
  Settings,
  Share2,
  ShieldCheck,
  ShoppingCart,
  Smile,
  Speech,
  Square,
  SquareCheck,
  SquareCheckBig,
  SquarePen,
  Star,
  StickyNote,
  Sun,
  Table,
  Tag,
  Target,
  TextCursorInput,
  Trash2,
  TrendingUp,
  Triangle,
  TriangleAlert,
  Type,
  Undo2,
  Unlink,
  Upload,
  User,
  Users,
  UtensilsCrossed,
  Workflow,
  Wrench,
  X,
  type LucideIcon,
} from 'lucide-react'

type IconComp = LucideIcon

/** `bx-*` → lucide 组件。**闸门 `check-icons` 保证用到的名字这里都有**
 *  （名字打错在 lucide 里的表现是渲染不出来，跟当初 `bx-magic-wand` 一个坑）。 */
export const ICONS: Record<string, IconComp> = {
  'bx-align-left': AlignLeft,
  'bx-window-open': AppWindow,
  'bx-left-arrow-alt': ArrowLeft,
  'bx-transfer': ArrowLeftRight,
  'bx-right-arrow-alt': ArrowRight,
  'bx-book': Book,
  'bx-bookmark': Bookmark,
  'bx-bookmark-plus': BookmarkPlus,
  'bx-bot': Bot,
  'bx-brain': Brain,
  'bx-briefcase': Briefcase,
  'bx-brush': Brush,
  'bx-buildings': Building2,
  'bx-calculator': Calculator,
  'bx-calendar': Calendar,
  'bx-calendar-event': CalendarDays,
  'bx-camera': Camera,
  'bx-car': Car,
  'bx-bar-chart-alt-2': ChartColumn,
  'bx-line-chart': ChartLine,
  'bx-check': Check,
  'bx-chevron-down': ChevronDown,
  'bx-chevron-left': ChevronLeft,
  'bx-chevron-right': ChevronRight,
  'bx-chevron-up': ChevronUp,
  'bx-collapse-vertical': ChevronsDownUp,
  'bx-chevrons-left': ChevronsLeft,
  'bx-chevrons-right': ChevronsRight,
  'bx-circle': Circle,
  'bx-check-circle': CircleCheck,
  'bx-dollar-circle': CircleDollarSign,
  'bx-help-circle': CircleHelp,
  'bx-pause-circle': CirclePause,
  'bx-question-mark': CircleQuestionMark,
  'bx-stop-circle': CircleStop,
  'bx-time-five': Clock,
  'bx-code-block': Code,
  'bx-code-alt': CodeXml,
  'bx-coffee': Coffee,
  'bx-columns': Columns2,
  'bx-command': Command,
  'bx-copy': Copy,
  'bx-duplicate': CopyPlus,
  'bx-subdirectory-right': CornerDownRight,
  'bx-chip': Cpu,
  'bx-crosshair': Crosshair,
  'bx-data': Database,
  'bx-download': Download,
  'bx-dumbbell': Dumbbell,
  'bx-dots-horizontal-rounded': Ellipsis,
  'bx-expand': Expand,
  'bx-link-external': ExternalLink,
  'bx-show': Eye,
  'bx-file-blank': File,
  'bx-file': FileText,
  'bx-copy-alt': Files,
  'bx-filter-alt': Filter,
  'bx-flag': Flag,
  'bx-folder': Folder,
  'bx-folder-open': FolderOpen,
  'bx-git-branch': GitBranch,
  'bx-git-commit': GitCommitHorizontal,
  'bx-git-compare': GitCompare,
  'bx-git-merge': GitMerge,
  'bx-hash': Hash,
  'bx-heading': Heading,
  'bx-headphone': Headphones,
  'bx-heart': Heart,
  'bx-history': History,
  'bx-home': House,
  'bx-image': Image,
  'bx-image-add': ImagePlus,
  'bx-image-alt': Images,
  'bx-import': Import,
  'bx-info-circle': Info,
  'bx-layer-plus': Layers,
  'bx-category': LayoutGrid,
  'bx-leaf': Leaf,
  'bx-bulb': Lightbulb,
  'bx-link': Link,
  'bx-link-alt': Link2,
  'bx-list-ul': List,
  'bx-list-check': ListChecks,
  'bx-list-ol': ListOrdered,
  'bx-task': ListTodo,
  'bx-loader-circle': LoaderCircle,
  'bx-lock': Lock,
  'bx-envelope': Mail,
  'bx-map': Map,
  'bx-fullscreen': Maximize,
  'bx-merge': Merge,
  'bx-message-dots': MessageCircleMore,
  'bx-chat': MessageSquare,
  'bx-conversation': MessagesSquare,
  'bx-microphone': Mic,
  'bx-microphone-off': MicOff,
  'bx-desktop': Monitor,
  'bx-moon': Moon,
  'bx-expand-horizontal': MoveHorizontal,
  'bx-music': Music,
  'bx-notepad': NotebookText,
  'bx-package': Package,
  'bx-paint': PaintBucket,
  'bx-brush-alt': Paintbrush,
  'bx-palette': Palette,
  'bx-window-alt': PanelTop,
  'bx-edit-alt': PenLine,
  'bx-pen': PenTool,
  'bx-pencil': Pencil,
  'bx-phone': Phone,
  'bx-pin': Pin,
  'bxs-pin': Pin,
  'bx-play': Play,
  'bx-plus': Plus,
  'bx-slideshow': Presentation,
  'bx-extension': Puzzle,
  'bxs-quote-left': Quote,
  'bx-refresh': RefreshCw,
  'bx-rocket': Rocket,
  'bx-reset': RotateCcw,
  'bx-save': Save,
  'bx-search': Search,
  'bx-paper-plane': Send,
  'bx-cog': Settings,
  'bx-share': Share2,
  'bx-check-shield': ShieldCheck,
  'bx-cart': ShoppingCart,
  'bx-smile': Smile,
  'bx-user-voice': Speech,
  'bx-checkbox': Square,
  'bx-stop': Square,
  'bx-check-square': SquareCheck,
  'bx-checkbox-checked': SquareCheckBig,
  'bx-edit': SquarePen,
  'bx-star': Star,
  'bx-note': StickyNote,
  'bx-sun': Sun,
  'bx-table': Table,
  'bx-purchase-tag': Tag,
  'bx-target-lock': Target,
  'bx-rename': TextCursorInput,
  'bx-trash': Trash2,
  'bx-trending-up': TrendingUp,
  'bx-shape-triangle': Triangle,
  'bx-error': TriangleAlert,
  'bx-text': Type,
  'bx-undo': Undo2,
  'bx-unlink': Unlink,
  'bx-export': Upload,
  'bx-user': User,
  'bx-group': Users,
  'bx-food-menu': UtensilsCrossed,
  'bx-network-chart': Workflow,
  'bx-wrench': Wrench,
  'bx-x': X,
}

export type IconProps = {
  /** `bx-*` 名字。取值可以是常量表里来的，也可以是数据库里存的。 */
  n: string
  className?: string
  style?: React.CSSProperties
  strokeWidth?: number
  title?: string
}

export default function Icon({ n, className, style, strokeWidth, title }: IconProps) {
  const C = ICONS[n]
  // 名字不认识时**什么都不画**，而不是留一个占位方块：
  // 一个画不出来的图标已经够糟，再加一个方块只是更糟（第 713 轮）。
  if (!C) return null
  return (
    <C className={'bx' + (className ? ' ' + className : '')}
       size="1em" strokeWidth={strokeWidth} style={style} aria-hidden={title ? undefined : true}>
      {title ? <title>{title}</title> : null}
    </C>
  )
}
